# .github/workflows/lint-openapi.yml
name: Lint OpenAPI Spec

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g @stoplight/spectral-cli
      - run: spectral lint docs/swagger.yaml
